---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP FLI 문서
    url: "/index.html"
  - section: release-notes
  - section: san-migration
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
