---
permalink: phases/remediation-windows.html 
sidebar: sidebar 
keywords: ontap, fli, foreign lun import, windows host, pre-migration, offline fli, online fli 
summary: Windows 호스트에서 ONTAP FLI 마이그레이션을 실행하기 전에 다음 사전 마이그레이션 단계를 완료하십시오. 오프라인 마이그레이션과 온라인 마이그레이션에 대한 단계가 각각 다릅니다. 
---
= ONTAP FLI Windows 호스트 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 호스트에서 ONTAP FLI 마이그레이션을 실행하기 전에 다음 사전 마이그레이션 단계를 완료하십시오. 오프라인 마이그레이션과 온라인 마이그레이션에 대한 단계가 각각 다릅니다.



== 사전 마이그레이션 - 오프라인 FLI

이 단계는 오프라인 및 온라인 FLI 모두에 적용됩니다. Windows 호스트에서 소스 LUN의 매핑을 해제하기 전에 다음 호스트 측 준비 작업을 완료하십시오.

[cols="4"]
|===
| 파일 시스템 디바이스 | 물리적 드라이브(파일 시스템 없음) | WSFC(WFC) | Hyper V 


| 1단계: 마이그레이션을 위해 계획된 파일 시스템 디스크 식별 | 1단계: 마이그레이션 대상 물리적 디스크를 식별합니다 | 1단계: 마이그레이션을 위해 계획된 클러스터 디스크 식별 | 1단계: 가상 머신의 모든 애플리케이션을 중지하고 가상 머신을 종료합니다. 


| 2단계: 애플리케이션을 정상적으로 종료합니다 | 2단계 애플리케이션을 정상적으로 종료합니다 | 2단계 애플리케이션을 정상적으로 종료합니다 | 2단계: 호스트에서 디스크를 오프라인으로 전환합니다. 


| 3단계: 디스크를 오프라인으로 전환합니다 |  | 3단계: 클러스터를 종료하고 모든 클러스터 노드에서 클러스터 서비스를 중지합니다 | 3단계: 호스트에서 모든 LUN의 매핑을 해제합니다. 
|===


=== 파일 시스템 디바이스

.단계
. 마이그레이션 예정인 파일 시스템 디스크를 식별합니다.
+
Get-Disk | Format-Table Number, FriendlyName, Size, PartitionStyle

. 애플리케이션을 정상적으로 종료하십시오.
+
Stop-Service -Name <ServiceName>

. 디스크를 오프라인 상태로 전환합니다.
+
Set-Disk -Number <DiskNumber> -IsOffline $true





=== 물리적 드라이브(파일 시스템 없음)

.단계
. 마이그레이션을 계획한 물리적 디스크를 식별합니다.
+
Get-PhysicalDisk | Format-Table FriendlyName, Size, MediaType

. 애플리케이션을 정상적으로 종료하십시오.
+
Stop-Service -Name <ServiceName>





=== WSFC(Windows Server Failover Clustering)

.단계
. 마이그레이션 예정인 클러스터 디스크를 식별합니다.
+
Get-ClusterResource | Where-Object ResourceType -eq "Physical Disk"

. 애플리케이션을 정상적으로 종료하십시오.
+
ClusterResource 중지 -Name <ResourceName>

. 클러스터를 종료하고 모든 클러스터 노드에서 클러스터 서비스를 중지합니다.
+
Stop-Cluster -Name <ClusterName>





=== Hyper V

.단계
. 가상 머신에서 모든 애플리케이션을 중지하고 가상 머신을 종료하십시오.
+
Stop-VM -Name <VM_Name> -Force

. 호스트에서 디스크를 오프라인으로 전환합니다.
+
Set-Disk -Number <DiskNumber> -IsOffline $true

. 스토리지 어레이 측에서 호스트의 모든 LUN 매핑을 해제합니다.
. 디스크가 호스트에서 올바르게 제거되었는지 확인하십시오.
+
Get-Disk | Where-Object OperationalStatus -ne "Online"





== 사전 마이그레이션 - 온라인 FLI

다음은 온라인 FLI의 구체적인 단계이지만 이러한 단계 전에 사전 마이그레이션 - 오프라인 FLI의 단계를 수행해야 합니다.

NetApp LUN이 호스트에 프로비저닝된 후에는 다음 단계를 수행해야 합니다.

이 시점에서 LUN 가져오기는 이미 생성되었고, LUN은 호스트 igroup에 매핑되었으며, 호스트에서 iSCSI 또는 FC 이니시에이터가 로그인되어 있습니다.

오프라인 FLI의 경우 NetApp LUN은 오프라인 상태를 유지합니다.

[cols="2"]
|===
| 파일 시스템 디바이스 | 물리적 드라이브(파일 시스템 없음) 


| 1단계: 매핑된 모든 호스트의 스토리지를 다시 스캔합니다. | 1단계: 매핑된 모든 호스트의 스토리지를 다시 스캔합니다. 


| 2단계: 나열된 드라이브를 확인하고 디스크를 온라인 상태로 전환합니다. | 2단계: 필요한 애플리케이션에 물리적 디스크를 추가하고 시작합니다. 


| 3단계: 모든 파일 시스템 디스크가 사용 가능하고 정상적으로 작동하는지 확인합니다. |  


| 4단계: 필요한 애플리케이션을 시작하십시오. |  
|===


=== 파일 시스템 디바이스

.단계
. 매핑된 모든 호스트의 스토리지를 다시 스캔합니다.
+
Update-HostStorageCache

. 나열된 드라이브를 식별하고 디스크를 온라인 상태로 만드십시오.
+
[Source]
----
Get-Disk | Where-Object IsOffline -eq $true
Set-Disk -Number <DiskNumber> -IsOffline $false
----
. 파일 시스템 디스크가 모두 사용 가능하고 정상적으로 작동하는지 확인하십시오.
+
Get-Volume | Format-Table DriveLetter, FileSystemLabel, Size, SizeRemaining

. 필요한 애플리케이션을 시작합니다.
+
Start-Service -Name <ServiceName>





=== 물리적 드라이브(파일 시스템 없음)

.단계
. 매핑된 모든 호스트의 스토리지를 다시 스캔합니다.
+
Update-HostStorageCache

. 필요한 애플리케이션에 물리적 디스크를 추가하고 시작하십시오.
+
애플리케이션별 구성





=== WSFC

.단계
. 매핑된 모든 호스트의 스토리지를 다시 스캔합니다.
+
Update-HostStorageCache

. 나열된 드라이브를 식별하고 디스크를 온라인 상태로 만드십시오.
+
[Source]
----
Get-Disk | Where-Object IsOffline -eq $true
Set-Disk -Number <DiskNumber> -IsOffline $false
----
. 매핑된 모든 호스트에 드라이브가 사용 가능하고 온라인 상태인지 확인하십시오.
+
Get-ClusterResource | Where-Object ResourceType -eq "Physical Disk"

. WSFC 클러스터 애플리케이션을 시작하고 필요한 클러스터형 리소스를 구성합니다.
+
[Source]
----
Start-Cluster -Name <ClusterName>
Start-ClusterResource -Name <ResourceName>
----




=== Hyper V

.단계
. 디스크 관리를 다시 검색하면 모든 디스크가 연결됩니다.
+
Update-HostStorageCache

. 디스크를 선택하고 온라인 상태로 전환하십시오. 모든 디스크가 온라인 상태가 되고 원래 이름과 디스크 문자를 받게 됩니다.
+
[Source]
----
Get-Disk | Where-Object IsOffline -eq $true
Set-Disk -Number <DiskNumber> -IsOffline $false
----
. 가상 머신의 전원을 켜보십시오. 가상 머신이 문제없이 온라인 상태가 되어야 합니다.
+
Start-VM -Name <VM_Name>


