---
permalink: san-migration/concept_recommended_tools_for_data_migration.html 
sidebar: sidebar 
keywords: recommended, tools, data, migration 
summary: 서비스 툴은 원격 데이터 수집, 구성 및 스토리지 관리 작업과 같은 유용한 기능을 수행하기 위한 표준화된 방법을 제공합니다. 
---
= 데이터 마이그레이션을 위한 권장 툴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서비스 툴은 원격 데이터 수집, 구성 및 스토리지 관리 작업과 같은 유용한 기능을 수행하기 위한 표준화된 방법을 제공합니다.

다음 서비스 도구는 데이터를 수집하고 구문 분석하는 데 사용됩니다.

* * OneCollect *
+
웹 기반 UI 또는 CLI와 함께 제공되는 NetApp Active IQ OneCollect를 사용하면 SAN 및 NAS 환경 모두에서 스토리지, 호스트, 패브릭 및 스위치에서 데이터를 수집할 수 있습니다. 수집된 데이터는 문제 해결, 솔루션 검증, 데이터 마이그레이션 및 업그레이드 평가에 사용됩니다. 고객 환경과 관련된 진단 콘텐츠를 NetApp으로 전송하여 추가 분석을 수행하거나 사내로 분석할 수 있습니다.

* * NetApp 데이터 마이그레이션 Solaris 릴러 *
+
Solaris Relabeler는 마이그레이션 후 VTOC(Volume Table of Contents) 디스크의 ASCII 레이블을 업데이트하는 기능을 제공하는 명령줄 유틸리티입니다.

+
초기 VTOC 디스크 초기화 루틴 동안 Solaris format 명령은 디스크에 대한 SCSI 조회를 수행하고 공급업체별 정보(제조업체, 제품 및 버전)를 디스크 레이블에 기록합니다. 모든 추가 문의는 실제 장치가 아닌 디스크 레이블로 전달됩니다. 블록 수준 마이그레이션은 이 디스크 레이블을 새 디스크에 복사하고, 이전 SCSI 조회 데이터는 시스템 도구 및 로그에 계속 표시됩니다. eler는 마이그레이션 후 디스크를 새로운 조회 데이터로 업데이트합니다.



FLI 마이그레이션 프로젝트에는 다음과 같은 툴 및 유틸리티도 유용합니다.

* * 상호 운용성 매트릭스 *
+
상호 운용성 매트릭스 툴(IMT)은 NetApp, FlexArray, 타사 소프트웨어 구성요소의 상호 운용성 확인을 위해 사용되는 NetApp 웹 기반 유틸리티입니다.

* * ONTAP 시스템 관리자 *
+
ONTAP System Manager는 그래픽 인터페이스를 사용하여 NetApp FAS 시스템의 원격 스토리지 관리를 제공합니다.

* * OnCommand Workflow Automation *
+
WFA는 스토리지 워크플로우를 생성하고 스토리지 프로비저닝, 마이그레이션, 서비스 해제, 클론 복제 등의 스토리지 관리 작업을 자동화할 수 있는 소프트웨어 솔루션입니다.



* 관련 정보 *

https://mysupport.netapp.com/site/tools["NetApp 툴"]

http://mysupport.netapp.com/NOW/download/tools/ndcp/["NetApp 툴: 데이터 센터 플래너"]

https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61372["NetApp 설명서:OnCommand 시스템 관리자(최신 릴리즈)"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550["NetApp 설명서: OnCommand Workflow Automation(최신 릴리즈)"]
