---
permalink: san-migration/concept_migration_types_supported_by_foreign_lun_import.html 
sidebar: sidebar 
keywords: migration, types, supported, foreign, lun, import 
summary: FLI는 온라인, 오프라인, 전환 및 자동화의 4가지 주요 마이그레이션 워크플로 유형을 지원합니다. 사용할 워크플로는 구성 및 기타 요소에 따라 다릅니다. 
---
= 외부 LUN 가져오기에서 지원되는 마이그레이션 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI는 온라인, 오프라인, 전환 및 자동화의 4가지 주요 마이그레이션 워크플로 유형을 지원합니다. 사용할 워크플로는 구성 및 기타 요소에 따라 다릅니다.

* 온라인 마이그레이션에서 타사 어레이의 FLI를 사용하면 마이그레이션 중에 클라이언트 시스템이 온라인 상태로 유지됩니다(Windows, Linux 또는 ESXi 호스트 운영 체제 필요).
* 오프라인 마이그레이션 시 타사 어레이에서 FLI는 클라이언트 시스템을 오프라인 상태로 전환하고 데이터를 새 LUN에 복사한 후 다시 온라인 상태로 만듭니다.
* 전환 마이그레이션에서 FLI는 7-Mode에서 운영되는 ONTAP를 ONTAP로 전환합니다. 이 프로세스는 소스 배열이 ONTAP 인 경우를 제외하고 기능적으로 동일합니다. 전환 워크플로는 온라인 또는 오프라인 모드에서 사용할 수 있습니다.
* 자동 마이그레이션 시 FLI는 WFA(Workflow Automation) 소프트웨어를 사용하여 마이그레이션 프로세스의 일부를 자동화합니다. WFA를 사용하는 FLI는 온라인 또는 오프라인 모드에서 사용할 수 있습니다.


구조적으로 세 가지 마이그레이션과 전환 워크플로우가 상당히 유사합니다. 이 4가지 요소는 모두 NetApp의 FlexArray 기술을 활용하여 ONTAP 컨트롤러가 소스 어레이 앞에서 이니시에이터 역할을 수행하고, 이 위치를 사용하여 소스에서 대상 ONTAP 어레이의 LUN으로 블록 LUN 블록을 복제할 수 있게 합니다.

컷오버가 발생할 경우, 작업 중단 기간의 길이, 자동화를 사용할 때 또는 소스 어레이가 ONTAP 7-Mode 또는 타사 어레이를 실행하는 NetApp 스토리지인 경우 워크플로우와 그 차이점이 있습니다.
