---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: FLI 마이그레이션에서는 NetApp 스토리지에서 소스 스토리지 LUN을 액세스해야 합니다. 대상 스토리지의 이니시에이터 포트를 사용하여 소스 스토리지의 타겟 포트를 조닝하면 됩니다. 
---
= 타겟 및 이니시에이터 포트 조닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 마이그레이션에서는 NetApp 스토리지에서 소스 스토리지 LUN을 액세스해야 합니다. 대상 스토리지의 이니시에이터 포트를 사용하여 소스 스토리지의 타겟 포트를 조닝하면 됩니다.

기존 소스 스토리지와 호스트 간 존은 수정되지 않으며 마이그레이션 후 비활성화됩니다. 호스트에서 대상 스토리지로 마이그레이션된 LUN에 액세스할 수 있도록 호스트와 대상 스토리지 간에 스토리지 영역이 생성됩니다.

FLI를 사용하는 표준 마이그레이션 시나리오에서는 다음과 같은 네 가지 고유한 영역이 필요합니다.

* 영역 1: 소스 스토리지와 대상 스토리지(운영 패브릭 A)
* 존 2: 소스 스토리지와 대상 스토리지(운영 패브릭 B)
* 영역 3: 호스트와 대상 스토리지(운영 패브릭 A)
* 구역 4: 호스트와 대상 스토리지(운영 패브릭 B)


다음 조닝 모범 사례를 따르십시오.

* 동일한 존에서 소스 스토리지 타겟 포트와 대상 스토리지 타겟 포트를 혼합하지 마십시오.
* 대상 스토리지 이니시에이터 포트와 호스트 포트를 같은 존에 혼합하지 마십시오.
* 대상 스토리지 타겟과 이니시에이터 포트를 같은 존에 혼합하지 마십시오.
* 이중화를 위해 각 컨트롤러에서 최소 2개의 포트로 존을 설정합니다.
* NetApp에서는 단일 이니시에이터 및 단일 타겟 조닝을 사용할 것을 권장합니다.


[NOTE]
====
대상 스토리지 이니시에이터 포트를 사용하여 소스 스토리지 타겟 포트를 조닝한 후에는 storage array show 명령을 사용하여 대상 스토리지에 소스 스토리지가 표시됩니다. 스토리지 어레이가 처음 검색되면 NetApp 컨트롤러에 어레이가 자동으로 표시되지 않을 수 있습니다. ONTAP 이니시에이터 포트가 연결된 스위치 포트를 재설정하여 이 문제를 해결합니다.

====