---
permalink: san-migration/concept_initiator_group_configuration.html 
sidebar: sidebar 
keywords: initiator, group, configuration 
summary: '올바른 작동을 위해서는 올바른 LUN 마스킹 구성이 중요합니다. ONTAP 스토리지의 모든 이니시에이터 포트(두 노드 모두)가 동일한 igroup에 상주해야 합니다.' 
---
= 이니시에이터 그룹 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
올바른 작동을 위해서는 올바른 LUN 마스킹 구성이 중요합니다. ONTAP 스토리지의 모든 이니시에이터 포트(두 노드 모두)가 동일한 igroup에 상주해야 합니다.

FLI 마이그레이션에서는 NetApp 스토리지에서 소스 스토리지 LUN을 액세스해야 합니다. 조닝(zoning)을 제외하고 액세스를 활성화하려면 대상 스토리지의 이니시에이터 포트에서 WWPN(Worldwide Port Name)을 사용하여 소스 스토리지에 이니시에이터 그룹을 생성해야 합니다.


NOTE: 이 섹션의 예에서는 HDS(Hitachi Data Systems) AMS 어레이를 사용하므로 외부 스토리지 명령은 마이그레이션할 타사 스토리지에 따라 다릅니다.

NetApp 어레이의 이니시에이터 그룹에 항상 ALUA(Asymmetric Logical Unit Access)를 사용하도록 설정하십시오.

이니시에이터 그룹은 공급업체 및 제품에 따라 다른 이름으로 이동합니다. 예를 들면 다음과 같습니다.

* Hitachi Data Systems(HDS)는 ""호스트 그룹""을 사용합니다.
* NetApp E-Series는 "'호스트 항목''을 사용합니다.
* EMC는 "이니시에이터 레코드" 또는 "스토리지 그룹"을 사용합니다.
* NetApp은 ""igroup.""을 사용합니다.


명명법에 관계없이 이니시에이터 그룹은 동일한 LUN 매핑을 공유하는 WWPN을 통해 이니시에이터를 식별하는 데 사용됩니다.

이니시에이터 그룹을 정의하려면 스토리지 설명서에서 LUN 마스킹(igroup/호스트 그룹/스토리지 그룹 등)을 설정하는 방법을 검토합니다. 타사 스토리지 구성에 대한 _FlexArray 가상화 구현 가이드 를 검토하여 타사 스토리지 구성 요구 사항을 확인할 수도 있습니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["타사 스토리지를 위한 FlexArray 가상화 구축"]
