---
permalink: san-migration/concept_migration_analyze_phase_workflow.html 
sidebar: sidebar 
keywords: analyze, phase, workflow 
summary: 분석 단계에서는 마이그레이션 계획 전에 해결해야 하는 항목을 중점적으로 다룹니다. 상호 운용성 매트릭스를 벗어나는 호스트 구성 세부 사항을 식별해야 합니다. 
---
= 단계 워크플로 분석
:icons: font
:imagesdir: ../media/


[role="lead"]
분석 단계에서는 마이그레이션 계획 전에 해결해야 하는 항목을 중점적으로 다룹니다. 상호 운용성 매트릭스를 벗어나는 호스트 구성 세부 사항을 식별해야 합니다.

각 호스트에 대해 타겟 구성(마이그레이션 후)이 식별되고 지원되지 않는 특정 구성 요소를 식별하기 위해 갭 분석이 수행됩니다. 호스트 분석은 완료되면 즉시 검토해야 합니다. 필수 업데이트로 인해 각 호스트에서 실행 중인 응용 프로그램과의 호환성이 깨질 수 있습니다.

일반적으로 필요한 호스트 변경은 실제 마이그레이션 이벤트가 발생할 때까지 적용되지 않습니다. 이는 유지 보수 기간을 예약해야 하는 일반적인 요구 사항으로 인해 발생하지만, 시스템 패치 및 HBA(호스트 버스 어댑터) 업데이트와 같이 가능한 경우 호스트 변경을 미리 수행하는 것이 위험하지 않은 경우가 많습니다. 또한 동일한 유지보수 이벤트를 사용하여 애플리케이션 업데이트와 함께 시스템 업데이트를 자주 수행합니다. 일반적으로 마이그레이션 전에 MPIO(다중 경로 I/O) 구성을 변경하면 현재 스토리지의 지원도 영향을 받습니다. 예를 들어 호스트에서 PowerPath를 제거하고 Linux에서 기본 MPIO 및 ALUA(Asymmetric Logical Unit Access)를 사용하도록 다시 구성하는 것은 현재 스토리지 구성에서 지원되지 않을 수 있습니다.

마이그레이션 후까지 MPIO 재구성을 지연하면 필요한 경우 롤백 프로세스가 간소화됩니다.

계획 단계 작업은 다음 표에 나열되어 있습니다.

[cols="2*"]
|===
| 구성 요소 | 작업 


 a| 
호스트
 a| 
. 각 호스트에 대한 갭 분석을 수행합니다. NetApp IMT에서 선택한 타겟 구성과 일치하는 필요한 핫 픽스/패치, OS 업데이트, HBA 드라이버 및 펌웨어 업그레이드를 식별합니다. 또한 이 호스트에 설치할 다른 NetApp 소프트웨어(SnapDrive ®, SnapManager ®)의 요구사항을 고려해야 합니다.
. 각 호스트(OS 구성, MPIO, HBA 세부 정보, 호스트 유틸리티 키트 버전)에 대한 타겟 구성(마이그레이션 후)을 결정합니다.
. 추가 NetApp 제품 요구사항(SnapDrive, SnapManager) 결정


|===
* 관련 정보 *

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성"]
