---
permalink: san-migration/create-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: ceate, lun import relationship, fli, offline migration 
summary: 외부 어레이에서 ONTAP 스토리지로 LUN을 마이그레이션하려면 먼저 LUN 가져오기 관계를 생성해야 합니다. LUN 가져오기 관계는 데이터 가져오기를 위해 소스 스토리지와 대상 스토리지 간에 영구적으로 연결되는 관계입니다. 
---
= ONTAP FLI 오프라인 마이그레이션을 위한 LUN 가져오기 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
외부 어레이에서 ONTAP 스토리지 시스템으로 LUN을 마이그레이션하려면 먼저 LUN 가져오기 관계를 생성해야 합니다. LUN 가져오기 관계는 데이터 가져오기를 위해 소스 스토리지와 대상 스토리지 간에 영구적으로 연결된 관계입니다. 소스 및 대상 엔드포인트는 LUN입니다.

FLI(Foreign LUN Import) 오프라인 마이그레이션을 위한 LUN 가져오기 관계를 생성하는 과정에는 ONTAP 에서 소스 어레이 LUN을 외래로 식별하고, 외래 LUN을 포함할 대상 볼륨을 생성 및 구성하고, 대상 LUN을 생성하고, 마지막으로 가져오기 관계를 설정하는 작업이 포함됩니다.

.시작하기 전에
다음 단계를 완료해야 합니다. link:prepare-foreign-lun-offline.html["FLI 오프라인 마이그레이션을 위해 외국 LUN을 준비하세요"] .



== 1단계: ONTAP 에서 소스 어레이 LUN을 외부로 식별

FLI 오프라인 마이그레이션을 시작하기 전에 ONTAP 에서 소스 어레이 LUN을 외부 LUN으로 식별해야 합니다.

.단계
. 외부 어레이에서 매핑된 소스 LUN을 나열한 다음 디스크 속성과 경로를 확인합니다.
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
----
+
케이블 연결에 따라 필요한 경로 수(각 소스 컨트롤러에 대한 경로 2개 이상)를 확인해야 합니다. 스토리지 LUN을 마스킹한 후 이벤트 로그도 확인해야 합니다.

+
다음 예에서는 Hitachi DF600F 어레이의 소스 LUN을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

----
. ONTAP 에서 일련 번호를 사용하여 소스 LUN을 외부로 표시합니다.
+
[source, cli]
----
storage disk set-foreign-lun -serial-number <lun_serial_number> -is-foreign true
----
+
다음 예에서는 Hitachi DF600F 어레이의 소스 LUN을 외부로 표시합니다.

+
[listing]
----
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542001E }
                   -is-foreign true
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542000E }
                   -is-foreign true
DataMig-ontap::*> storage disk set-foreign-lun { -serial-number 83017542000F }
                   -is-foreign true
----
. 소스 LUN이 외부 LUN으로 표시되어 있는지 확인합니다.
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
----
+
다음 예에서는 Hitachi DF600F 어레이의 소스 LUN이 외부로 표시된 것을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     true       foreign        false              83017542001E
HIT-1.3  -     true       foreign        false              83017542000E
HIT-1.4  -     true       foreign        false              83017542000F
3 entries were displayed.
----




== 2단계: 대상 볼륨 생성 및 구성

FLI 오프라인 마이그레이션에 대한 LUN 가져오기 관계를 생성하기 전에 외부 어레이에서 가져올 LUN을 포함할 볼륨을 ONTAP 스토리지 시스템에 생성해야 합니다.

.이 작업에 관하여
ONTAP 9.17.1부터 ASA r2 시스템에서 FLI 오프라인 마이그레이션을 사용한 외부 LUN 데이터 마이그레이션이 지원됩니다. ASA r2 시스템은 스토리지 계층 구현 방식에서 다른 ONTAP 시스템(ASA, AFF, FAS)과 다릅니다. ASA r2 시스템에서는 스토리지 유닛(LUN 또는 네임스페이스)이 생성될 때 볼륨이 자동으로 생성됩니다. 따라서 LUN 가져오기 관계를 생성하기 전에 볼륨을 생성할 필요가 없습니다. ASA r2 시스템을 사용하는 경우 이 단계를 건너뛸 수 있습니다.

자세히 알아보세요 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 시스템"^] .

.단계
. 대상 볼륨을 생성합니다.
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate> -size <volume_size> -snapshot-policy default
----
+
다음 예제에서는 이름이 지정된 볼륨을 생성합니다.  `winvol` 에  `aggr1` 100GB 크기의 집계입니다.

+
[listing]
----
DataMig-ontap::*> vol create -vserver datamig winvol aggr1 -size 100g
----
. 각 볼륨에서 기본 스냅샷 정책을 비활성화합니다.
+
[source, cli]
----
volume modify -vserver <SVM_name> -volume <volume_name> -snapshot-policy none
----
+
FLI 마이그레이션 전에 기본 스냅샷 복사본이 있는 경우 볼륨에는 변경된 데이터를 저장하기 위한 추가 공간이 필요합니다.

+
다음 예제에서는 기본 스냅샷 정책을 비활성화합니다.  `winvol` 용량.

+
[listing]
----
DataMig-ontap::> volume modify -vserver datamig -volume winvol -snapshot-policy none

Warning: You are changing the Snapshot policy on volume winvol to none.  Any Snapshot copies on this volume from the previous policy will not be deleted by
         this new Snapshot policy.
Do you want to continue? {y|n}: y
Volume modify successful on volume winvol of Vserver datamig.
----
. 각 볼륨에 대해 fraction_reserveoption을 0으로 설정하고 Snapshot 정책을 none으로 설정합니다.
+
[source, cli]
----
vol modify -vserver <SVM_name> -volume * -fractional-reserve 0 –snapshot-policy none
----
+
다음 예제에서는 다음을 설정합니다.  `fractional-reserve` 옵션  `0` 그리고 스냅샷 정책  `none` Datamig SVM의 모든 볼륨에 대해.

+
[listing]
----
DataMig-ontap::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. 볼륨 설정을 확인하세요.
+
[source, cli]
----
volume show -vserver <SVM_name> -volume * -fields fractional-reserve,snapshot-policy
----
+
팩션 예비 및 스냅샷 정책 설정은 다음과 같아야 합니다.  `0` 그리고  `none` 각각.

. 기존 스냅샷 복사본을 삭제합니다
+
[source, cli]
----
set advanced; snap delete –vserver <SVM_name> –volume <volume_name> –snapshot * -force true
----
+
[NOTE]
====
FLI 마이그레이션은 대상 LUN의 모든 블록을 수정합니다. FLI 마이그레이션 전에 볼륨에 기본 또는 기타 Snapshot 복사본이 있으면 볼륨이 가득 차게 됩니다. FLI 마이그레이션이 필요하기 전에 정책을 변경하고 기존 Snapshot 복사본을 제거합니다. 마이그레이션 후 스냅샷 정책을 다시 설정할 수 있습니다.

====




== 3단계: 대상 LUN 및 LUN 가져오기 관계 생성

FLI 오프라인 마이그레이션의 경우 ONTAP 스토리지 시스템의 대상 LUN을 생성하여 igroup에 매핑해야 합니다. 그런 다음 LUN 가져오기 관계를 생성하기 전에 해당 LUN을 오프라인으로 설정해야 합니다.

.이 작업에 관하여
ONTAP 9.17.1부터 FLI 오프라인 마이그레이션을 사용하여 외부 LUN의 데이터 마이그레이션이 지원됩니다 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 시스템"^]. ASA r2 시스템은 스토리지 계층 구현 방식에서 다른 ONTAP 시스템(ASA, AFF, FAS)과 다릅니다. ASA 시스템에서는 스토리지 유닛(LUN 또는 네임스페이스)이 생성될 때 볼륨이 자동으로 생성됩니다. 각 볼륨에는 스토리지 유닛이 하나만 포함됩니다. 따라서 ASA r2 시스템의 경우 볼륨 이름을 지정할 필요가 없습니다.  `-path` LUN을 생성할 때 옵션을 사용하는 대신 저장 장치 경로를 포함해야 합니다.

.단계
. 대상 LUN을 생성합니다.
+
[source, cli]
----
lun create -vserver <SVM_name> -path <volume_path|storage_unit_path> -ostype <os_type> -foreign-disk <serial_number>
----
+
다음 예제에서는 LUN을 생성합니다.  `datamig` 지정된 경로와 외부 디스크 일련 번호가 있는 SVM .  `-ostype` 옵션은 LUN의 운영 체제 유형을 지정합니다.

+
[listing]
----
DataMig-ontap::*> lun create -vserver datamig -path /vol/winvol/bootlun -ostype windows_2008 -foreign-disk 83017542001E

Created a LUN of size 40g (42949672960)

Created a LUN of size 20g (21474836480)
DataMig-ontap::*> lun create -vserver datamig -path /vol/linuxvol/lvmlun1 -ostype linux -foreign-disk 830175420011

Created a LUN of size 2g (2147483648)
DataMig-ontap::*> lun create -vserver datamig -path /vol/esxvol/bootlun -ostype vmware -foreign-disk 830175420014

Created a LUN of size 20g (21474836480)
----
+
[NOTE]
====
그만큼  `lun create` 이 명령은 파티션 오프셋을 기반으로 LUN 크기와 정렬을 감지하고, foreign-disk 옵션을 사용하여 LUN을 생성합니다. 일부 I/O는 항상 부분 쓰기로 나타나 정렬이 잘못되어 보일 수 있습니다. 이러한 예로는 데이터베이스 로그가 있습니다.

====
. 새로 생성된 LUN의 크기와 소스 LUN을 확인합니다.
+
[source, cli]
----
lun show -vserver <SVM_name> -fields vserver, path, state, mapped, type, size
----
+
다음 예에서는 생성된 LUN을 보여줍니다.  `datamig` 경로, 상태, 매핑된 상태, 유형, 크기가 있는 SVM입니다.

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig

Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  unmapped vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  unmapped linux         2GB
datamig   /vol/esxvol/solrdmplun          online  unmapped solaris       2GB
datamig   /vol/winvol/gdrive              online  unmapped windows_2008  3GB
4 entries were displayed.
----
. ONTAP 9.15.1 이상을 실행하는 경우 새로 생성된 LUN에 대한 공간 할당을 비활성화합니다.
+
ONTAP 9.15.1 이상에서는 새로 생성된 LUN에 대해 기본적으로 공간 할당이 활성화됩니다.

+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation disabled
----
. 공간 할당이 비활성화되었는지 확인하세요.
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. 프로토콜 FCP의 호스트 igroup을 만들고 호스트 개시자를 추가합니다.
+
[source, cli]
----
lun igroup create -ostype <os_type> -protocol fcp -vserver <SVM_name> -igroup <igroup_name> -initiator <initiator_wwpn1>,<initiator_wwpn2>
----
+
사이트 조사 계획 워크시트의 스토리지 그룹 섹션에서 개시자 WWPN을 찾으세요.

+
다음 예제에서는 지정된 운영 체제 유형과 초기자를 사용하여 대상 LUN에 대한 igroup을 생성합니다.

+
[listing]
----
DataMig-ontap::*> lun igroup create -ostype windows -protocol fcp -vserver datamig -igroup dm-rx200s6-21 -initiator 21:00:00:24:ff:30:14:c4,21:00:00:24:ff:30:14:c5

DataMig-ontap::*> lun igroup create -ostype linux -protocol fcp -vserver datamig  -igroup dm-rx200s6-22 -initiator 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84

DataMig-ontap::*> lun igroup create -ostype vmware -protocol fcp -vserver datamig -igroup dm-rx200s6-20 -initiator 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb
----
+
[NOTE]
====
소스와 동일한 LUN ID를 사용합니다. 사이트 조사 계획 워크시트의 소스 LUN 섹션을 참조하십시오.

====
. 대상 LUN을 igroup에 매핑합니다.
+
[source, cli]
----
lun map -vserver <SVM_name> -path <volume_path|storage_unit_path> -igroup <igroup_name> -lun-id <lun_id>
----
+
다음 예제에서는 대상 LUN을 지정된 경로와 LUN ID를 사용하여 해당 igroup에 매핑합니다.

+
[listing]
----
DataMig-ontap::*> lun map -vserver datamig -path /vol/winvol/bootlun -igroup dm-rx200s6-21 -lun-id 0
DataMig-ontap::*> lun map -vserver datamig -path /vol/linuxvol/bootlun -igroup dm-rx200s6-22 -lun-id 0
DataMig-ontap::*> lun map -vserver datamig -path /vol/esxvol/bootlun -igroup dm-rx200s6-20 -lun-id 0
----
. 대상 LUN을 오프라인 상태로 전환합니다.
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
다음 예제에서는 대상 LUN을 오프라인으로 설정합니다.  `datamig` SVM(서비스 가상 머신)

+
[listing]
----
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/bootlun
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/linuxrdmvlun
DataMig-ontap::*> lun offline -vserver datamig -path /vol/esxvol/solrdmplun
----
. 대상 LUN과 소스 LUN 사이에 LUN 가져오기 관계를 생성합니다.
+
[source, cli]
----
lun import create -vserver <SVM_name> -path <volume_path|storage_unit_path> -foreign-disk <serial_number>
----
+
다음 예제에서는 대상 LUN에 대한 LUN 가져오기 관계를 생성합니다.  `datamig` 각각의 경로와 외부 디스크 일련 번호가 있는 SVM입니다.

+
[listing]
----
DataMig-ontap::*> lun import create -vserver datamig -path /vol/winvol/bootlun -foreign-disk 83017542001E
DataMig-ontap::*> lun import create -vserver datamig -path /vol/linuxvol/ext3lun -foreign-disk 830175420013
DataMig-ontap::*> lun import create -vserver datamig -path /vol/esxvol/linuxrdmvlun -foreign-disk 830175420018
DataMig-ontap::*> lun import create -vserver datamig -path /vol/esxvol/solrdmplun -foreign-disk 830175420019
----
. LUN 가져오기 관계가 생성되었는지 확인하세요.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, operation, admin-state, operational-state, percent-complete
----
+
다음 예에서는 대상 LUN에 대해 생성된 LUN 가져오기 관계를 보여줍니다.  `datamig` 각각의 외부 디스크와 경로를 포함하는 SVM입니다.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542000E   /vol/winvol/fdrive  import    stopped
                                                           stopped            0
datamig 83017542000F   /vol/winvol/gdrive  import    stopped
                                                           stopped            0
datamig 830175420010   /vol/linuxvol/bootlun
                                           import    stopped
                                                           stopped            0
3 entries were displayed.
----


.다음은 무엇인가요?
link:task_fli_offline_importing_the_data.html["외부 LUN에서 ONTAP LUN으로 데이터 가져오기"] .

.관련 정보
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["정렬되지 않은 I/O에 대해 자세히 알아보세요"] .
* https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html["SAN 프로토콜에 대한 공간 할당 활성화에 대해 자세히 알아보세요."] .

