---
permalink: san-migration/map-source-lun-to-destination-online-migration.html 
sidebar: sidebar 
keywords: fli online, perform, disruptive, cutover 
summary: 이 예는 FLI 온라인 마이그레이션 프로세스에서 무중단 컷오버를 수행하는 일반적인 단계를 보여줍니다. 
---
= FLI 온라인 마이그레이션을 위해 소스 LUN을 ONTAP 어레이에 매핑합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
외부 어레이 LUN에서 데이터를 가져오려면 먼저 외부 어레이에서 LUN의 매핑을 해제하고 ONTAP 스토리지 시스템에 다시 매핑해야 합니다. 외부 어레이에서 LUN 매핑을 해제하는 명령은 어레이 공급업체에 따라 다릅니다. 전체 프로세스에 대한 자세한 내용은 제공된 단계를 따르고, 특정 명령은 외부 어레이 설명서를 참조하십시오.

.시작하기 전에
igroup에서 호스트(이니시에이터)를 제거하면 해당 igroup에 매핑된 모든 LUN에 영향을 미칩니다. 외부 어레이의 다른 LUN에 영향을 미치지 않도록 마이그레이션하는 LUN이 해당 igroup에 매핑된 유일한 LUN이어야 합니다. igroup을 공유하는 다른 LUN이 있는 경우, 해당 LUN을 다른 igroup에 다시 매핑하거나 마이그레이션할 LUN에 맞는 새 igroup을 만드십시오. 해당 명령은 공급업체 설명서를 참조하십시오.

.단계
. 외부 스토리지에서 소스 LUN이 매핑되는 스토리지 그룹을 표시합니다.
+
해당 명령에 대한 자세한 내용은 공급업체 설명서를 참조하십시오.

. 가져오는 LUN이 ESXi 호스트용인 경우 지침을 검토하고 따르십시오. link:reference_esxi_caw_ats_remediation.html["ESXi caw/ATS 개선"] .
. 호스트에서 소스 LUN 매핑을 해제합니다.
+
[NOTE]
====
매핑 해제 명령이 실행된 직후 중단이 시작됩니다. 일반적으로 중단 기간은 분 단위로 측정할 수 있습니다. 중단 기간은 새 NetApp 타겟의 호스트를 재가리키고 LUN을 검색하는 데 걸린 시간입니다.

====
. 호스트 이니시에이터가 더 이상 존재하지 않는지 확인합니다.
. ONTAP 클러스터에서 대상 LUN을 온라인 상태로 전환하고 매핑되었는지 확인합니다.
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. LUN이 온라인 상태인지 확인합니다.
+
[source, cli]
----
lun show -vserver <SVM_name>
----
. 호스트에서 디스크를 재검색하고 ONTAP 대상에서 LUN을 찾은 다음 DSM이 LUN을 확보했는지 확인합니다.
+
[NOTE]
====
여기서 중단 기간이 종료됩니다.

====
. 모든 예상 경로를 볼 수 있는지 확인하고 이벤트 로그를 확인하여 오류가 없는지 확인합니다.


.결과
분석 및 계획 단계에서 파악된, 중단을 유발하는 호스트 수정 작업이 아직 진행 중이지 않은 한, 이 마이그레이션의 중단 부분은 완료된 것입니다.

LUN이 온라인 상태로 매핑되고 호스트에서 새로운 ONTAP 호스팅 LUN을 마운트할 수 있습니다. 읽기는 ONTAP 어레이를 통해 소스 LUN으로 전달되고, 쓰기는 새로운 ONTAP 호스팅 LUN과 원본 소스 LUN 모두에 기록됩니다. 마이그레이션이 완료되고 LUN 관계가 끊어질 때까지 소스 LUN과 대상 LUN은 동기화된 상태를 유지합니다.

.다음은 무엇인가요?
link:task_fli_online_importing_the_data.html["외부 LUN에서 데이터 가져오기"] .
