---
permalink: san-migration/reference_site_survey_and_planning_worksheet_questionnaire_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, questionnaire tab 
summary: 사이트 조사 및 계획 워크시트의 일부로, 초기 마이그레이션 설문지의 마이그레이션 프로젝트 정보가 포함된 탭이 있어야 합니다. 
---
= 사이트 조사 및 계획 워크시트 질의 응답서 탭
:icons: font
:imagesdir: ../media/


[role="lead"]
사이트 조사 및 계획 워크시트의 일부로, 초기 마이그레이션 설문지의 마이그레이션 프로젝트 정보가 포함된 탭이 있어야 합니다.

다음은 질의 응답서 탭을 설정하는 방법의 예입니다.

|===
3+| 마이그레이션 프로젝트 정보 


 a| 
프로젝트 유형
 a| 
☐ 데이터 마이그레이션

☐ 기타
 a| 



 a| 
데이터 마이그레이션 목표
 a| 
&#91;목표 및 #93;
 a| 



 a| 
소스 디바이스
 a| 
스토리지: [스토리지 유형]

아니요 장치 수: [아니오. 어레이 수]

씬 프로비저닝: ☐ 예 ☐ 아니요
 a| 
모든 장치를 열거합니다



 a| 
클라이언트 장치
 a| 
운영 체제: [OS 버전]

SAN 부트: ☐ 예 ☐ 아니요

MPIO: [MPIO 버전]

HBA: [HBA 공급업체, 모델, 펌웨어]
 a| 



 a| 
패브릭 스위치
 a| 
공급업체:

모델:

펌웨어:

아니요 포트 수:
 a| 



 a| 
현재 프로토콜
 a| 
☐ FCP

☐ iSCSI
 a| 



 a| 
볼륨 관리자
 a| 
공급업체:

제품:

버전:
 a| 



 a| 
대상 장치(스토리지)
 a| 
스토리지: [스토리지]

아니요 [번호]

씬 프로비저닝: ☐ 예 ☐ 아니요
 a| 
이 서비스의 경우 NetApp 파일러만 해당됩니다



 a| 
마이그레이션할 데이터 양의 크기(TB)
 a| 
&#91; 데이터 양 &#93;
 a| 
요약 및 세부 정보(각 소스 디바이스)



 a| 
LUN 수입니다
 a| 
&#91; LUN 수 &#93;
 a| 
요약 및 세부 정보(각 소스 디바이스)



 a| 
데이터 재구성
 a| 
☐ 예 ☐ 아니오
 a| 
고객이 마이그레이션의 일부로 볼륨/디렉토리/폴더/파일을 다른 데이터 구조로 이동하기를 원합니까?



 a| 
운전 정지 기대
 a| 
운영 중단 윈도우

☐ 사전 정의 ☐ 유연함

표준 유지 보수 윈도우 정책: [INFO]
 a| 
사용 가능한 중단 횟수 및 기간입니다. 유지 보수 기간이 있는 경우 나열하십시오.



 a| 
원하는 완료 시간 프레임
 a| 
&#91; 원하는 완료 시간 프레임 &#93;&#91; 시간 민감도 &#93;
 a| 



 a| 
기타 관련 정보
 a| 
&#91; 기타 관련 정보 &#93;
 a| 



 a| 
고객 조직 이름 및 위치(시/도)
 a| 
 a| 

|===