---
permalink: san-migration/reference_site_survey_and_planning_worksheet_sds_cli_scripts_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, sds cli scripts tab 
summary: 사이트 조사 및 계획 워크시트의 일부로 SDS CLI 스크립트에 대한 정보가 포함된 탭이 있어야 합니다. 
---
= 사이트 조사 및 계획 워크시트 SDS CLI 스크립트 탭
:icons: font
:imagesdir: ../media/


[role="lead"]
사이트 조사 및 계획 워크시트의 일부로 SDS CLI 스크립트에 대한 정보가 포함된 탭이 있어야 합니다.

다음은 SDS CLI 스크립트 탭을 설정하는 방법의 예입니다.

|===
| 컨트롤러 1 | 컨트롤러 2 


 a| 
볼륨 크기 vol0 aggr0 108g
 a| 



 a| 
스냅 예약 bootcampvol 0
 a| 



 a| 
스냅 예약 vol0 20
 a| 



 a| 
자동 삭제 부트캠프vol을 켭니다
 a| 



 a| 
스냅 자동 삭제 부트캠프 볼륨 헌신을 시도해 보십시오
 a| 



 a| 
스냅 자동 삭제 bootcamvol 트리거 볼륨
 a| 



 a| 
스냅 자동 삭제 bootcampvol target_free_space 20
 a| 



 a| 
스냅 자동 삭제 bootcampvol defer_delete user_created
 a| 



 a| 
스냅 자동 삭제 vol0을 설정합니다
 a| 



 a| 
스냅 자동 삭제 vol0 헌신을 시도하십시오
 a| 



 a| 
스냅 자동 삭제 vol0 트리거 볼륨
 a| 



 a| 
스냅 자동 삭제 vol0 target_free_space 20
 a| 



 a| 
스냅 자동 삭제 vol0 defer_delete user_created
 a| 



 a| 
볼륨 자동 크기 조정 bootcampvol이 켜져 있습니다
 a| 



 a| 
볼륨 자동 크기 조정 vol0이 켜져 있습니다
 a| 



 a| 
볼륨 옵션 bootcampvol try_first volume_grow
 a| 



 a| 
볼륨 옵션 bootcampvol fractional_reserve 100
 a| 



 a| 
볼륨 옵션 vol0 try_first volume_grow
 a| 



 a| 
볼륨 옵션 vol0 fractional_reserve 100
 a| 



 a| 
Qtree 보안/vol/bootcampvol UNIX
 a| 



 a| 
Qtree 보안/vol/vol0 NTFS
 a| 



 a| 
스냅 sched bootcampvol 0 0 0
 a| 



 a| 
스냅 sched vol0 0 2 6 @ 8,12,16,20
 a| 



 a| 
LUN이 IGroup에 매핑되지 않았으므로 /vol/qavol_Narayan/TestLUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/DM25_boot_LUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/DM25_data1_LUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/DM25_data2_LUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm26_boot_lun에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm26_data1_lun에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm26_data2_LUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm27_boot_lun에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm27_data1_lun에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 



 a| 
LUN이 iGroup에 매핑되지 않았으므로 /vol/bootcampvol/dm27_data2_LUN에 대해 # LUN 매핑을 건너뛰었습니다.
 a| 

|===