---
permalink: san-migration/remove-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 검증 작업은 선택 사항이지만 권장됩니다. 소스 LUN과 대상 LUN의 블록별 비교입니다. 마이그레이션 시간보다 작업이 거의 비슷하거나 약간 더 오래 걸리는지 확인합니다. 
---
= ONTAP FLI 오프라인 마이그레이션 후 LUN 가져오기 관계 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI(Foreign LUN Import) 오프라인 마이그레이션이 완료되면 LUN 가져오기 관계를 안전하게 제거할 수 있습니다. 이제 호스트는 새 ONTAP LUN에 대한 모든 I/O를 위해 새 NetApp 어레이에 액세스하며, 소스 LUN은 더 이상 사용되지 않으므로 가져오기 관계는 더 이상 필요하지 않습니다.

ONTAP 9.17.1부터 FLI 오프라인 마이그레이션을 사용하여 외부 LUN의 데이터 마이그레이션이 지원됩니다link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 시스템"^]. ASA r2 시스템은 스토리지 계층 구현 방식에서 다른 ONTAP 시스템(ASA, AFF, FAS)과 다릅니다. ASA 시스템에서는 스토리지 유닛(LUN 또는 네임스페이스)이 생성될 때 볼륨이 자동으로 생성됩니다. 각 볼륨에는 스토리지 유닛이 하나만 포함됩니다. 따라서 ASA r2 시스템의 경우 볼륨 이름을 지정할 필요가 없습니다.  `-path` LUN을 생성할 때 옵션을 사용하는 대신 저장 장치 경로를 포함해야 합니다.

.단계
. 데이터 가져오기 작업을 제거하려면 가져오기 관계를 삭제하세요.
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
이 예제에서는 *winvol* 볼륨과 *datamig* SVM에서 *bootlun*, *fdrive* 및 *gdrive*라는 LUN에 대한 가져오기 관계를 삭제하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. 가져오기 작업이 삭제되었는지 확인하세요.
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
+
이 예에서는 *datamig* SVM에 대한 가져오기 작업이 삭제되었는지 확인하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
There are no entries matching your query.
----
. 외부 LUN 속성을 false로 표시합니다.
+
[source, cli]
----
storage disk modify -serial-number <serial_number> -is-foreign false
----
+
이 예에서는 외부 LUN 속성을 표시하는 명령을 보여줍니다.  `false` *winvol* 볼륨과 *datamig* SVM에 있는 *bootlun*, *fdrive* 및 *gdrive*라는 LUN에 대해.

+
[listing]
----
DataMig-ontap::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. 외부 LUN이 다음과 같이 표시되어 있는지 확인하십시오.  `false` .
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, import-in-progress, is-foreign
----
+
이 예에서는 외부 LUN이 다음과 같이 표시되었는지 확인하는 명령을 보여줍니다.  `false` *HITACHI_DF600F_1* 어레이에서.

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. 대상 LUN을 온라인으로 전환합니다.
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
이 예제에서는 *winvol* 볼륨과 *datamig* SVM에서 *bootlun*, *fdrive*, *gdrive*라는 LUN에 대한 대상 LUN을 온라인으로 가져오는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. LUN이 온라인 상태인지 확인합니다.
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
이 예에서는 *datamig* SVM에 대한 LUN이 온라인인지 확인하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
. 선택적으로 이벤트 로그를 보고 마이그레이션 결과를 확인하세요.
+
[source, cli]
----
event log show –event fli*
----
+
이 예제에서는 FLI 마이그레이션 결과에 대한 이벤트 로그를 보는 명령의 샘플 출력을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.다음은 무엇인가요?
link:concept_fli_offline_post_migration_tasks.html["FLI 오프라인 마이그레이션에 대한 마이그레이션 후 작업 수행"] .
