---
permalink: san-migration/task_fli_online_preparing_the_lun_path.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: FLI 온라인 마이그레이션을 준비하기 위해 호스트 및 소스 LUN 경로와 기타 세부 정보를 확인합니다. 
---
= FLI 온라인: LUN 경로 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 온라인 마이그레이션을 준비하기 위해 호스트 및 소스 LUN 경로와 기타 세부 정보를 확인합니다.

.단계
. ONTAP에서 권한 수준을 '고급'으로 변경합니다.
+
[listing]
----
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. 소스 어레이가 대상 컨트롤러에서 표시되는지 확인합니다.
+
[listing]
----

        cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. 소스 LUN 세부 정보를 표시합니다.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. 소스 스토리지가 모든 이니시에이터 포트를 통해 검색되는지 확인합니다.
+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
+
[NOTE]
====
다음 출력에서 단어 래핑은 의미가 없습니다.

====
. 소스 스토리지에서 매핑된 LUN을 나열합니다. 디스크 속성 및 경로를 확인합니다.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. 소스 LUN을 봅니다.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. 소스 LUN을 외부 LUN으로 표시합니다.
+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. 소스 LUN이 외부 LUN으로 표시되어 있는지 확인합니다.
+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. FLI LUN 임포트 명령에 일련 번호가 사용됩니다. 모든 외부 LUN 및 해당 일련 번호를 나열합니다.
+
[listing]
----
cluster::*> storage disk show -container-type foreign -fields serial-number
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----
. 대상 볼륨을 생성합니다.
+
[listing]
----
cluster::*> vol create -vserver fli -volume fli_vol -aggregate aggr1 -size 2t
[Job 13888] Job succeeded: Successful
----
. 볼륨을 확인합니다.
+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. 각 볼륨에 fraction_reserveoption을 "0"으로 설정하고 스냅샷 정책을 "없음"으로 설정합니다.
+
[listing]
----
cluster::*> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. 볼륨 설정을 확인합니다.
+
[listing]
----
cluster::*> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. 기존 스냅샷 복사본을 삭제합니다
+
[listing]
----
cluster::*> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
FLI 마이그레이션은 대상 LUN의 모든 블록을 수정합니다. FLI 마이그레이션 전에 볼륨에 기본 또는 기타 Snapshot 복사본이 있으면 볼륨이 가득 차게 됩니다. FLI 마이그레이션이 필요하기 전에 정책을 변경하고 기존 Snapshot 복사본을 제거합니다. 마이그레이션 후 스냅샷 정책을 다시 설정할 수 있습니다.

====
+
[NOTE]
====
LUN create 명령은 파티션 오프셋을 기반으로 크기와 정렬을 감지하고 그에 따라 외부 디스크 옵션을 사용하여 LUN을 생성합니다. I/O 정렬 불량을 검토하려면 NetApp 기술 자료 문서 * 정렬되지 않은 I/O란 무엇입니까? 를 참조하십시오. 또한 일부 I/O는 항상 부분 쓰기일 수 있으므로 잘못 정렬된 것처럼 보입니다. 예를 들어 데이터베이스 로그가 있습니다.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["정렬되지 않은 I/O란 무엇입니까?"]

. 타겟 LUN을 생성합니다. 'lun create' 명령은 파티션 오프셋을 기준으로 크기와 정렬을 감지하고 이에 따라 외래 디스크 인수를 사용하여 LUN을 생성합니다.
+
[listing]
----
cluster::*> lun create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -ostype windows_2008 -foreign-disk 600601603F103100662E70861000E511

Created a LUN of size 1t (1099511627776)
----
. 새 LUN을 확인합니다.
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. 호스트 이니시에이터가 있는 프로토콜 FCP의 igroup을 생성합니다.
+
[listing]
----
cluster::*> igroup create -vserver fli -igroup FLI -protocol fcp -ostype windows -initiator 10:00:00:00:c9:e6:e2:79
----
. 호스트가 새 igroup에 대한 모든 경로에 로그인하는지 확인합니다.
+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. 대상 LUN을 오프라인 상태로 전환합니다.
+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. 대상 LUN을 igroup에 매핑합니다.
+
[listing]
----
cluster::*> lun map -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -igroup FLI
----
. 새 LUN과 외부 LUN 간의 가져오기 관계를 생성합니다.
+
[listing]
----
cluster::*> lun import create -vserver fli -path /vol/fli_vol/OnlineFLI_LUN -foreign-disk 600601603F103100662E70861000E511
----

