---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 검증 작업은 선택 사항이지만 권장됩니다. 소스 LUN과 대상 LUN의 블록별 비교입니다. 마이그레이션 시간보다 작업이 거의 비슷하거나 약간 더 오래 걸리는지 확인합니다. 
---
= ONTAP FLI 오프라인 마이그레이션 결과 확인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN이 외부 어레이에서 ONTAP 스토리지 시스템으로 마이그레이션된 후, FLI는 소스 LUN과 대상 LUN을 블록 단위로 비교하여 마이그레이션이 완료되고 정확한지 확인할 수 있습니다. 마이그레이션 검증에는 마이그레이션과 거의 같은 시간(또는 약간 더 긴 시간)이 소요됩니다.

마이그레이션 확인은 필수는 아니지만 적극 권장됩니다.

.이 작업에 관하여
ONTAP 9.17.1부터 FLI 오프라인 마이그레이션을 사용하여 외부 LUN의 데이터 마이그레이션이 지원됩니다 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 시스템"^]. ASA r2 시스템은 스토리지 계층 구현 방식에서 다른 ONTAP 시스템(ASA, AFF, FAS)과 다릅니다. ASA 시스템에서는 스토리지 유닛(LUN 또는 네임스페이스)이 생성될 때 볼륨이 자동으로 생성됩니다. 각 볼륨에는 스토리지 유닛이 하나만 포함됩니다. 따라서 ASA r2 시스템의 경우 볼륨 이름을 지정할 필요가 없습니다.  `-path` LUN을 생성할 때 옵션을 사용하는 대신 저장 장치 경로를 포함해야 합니다.

.단계
. LUN 마이그레이션 검증을 시작합니다.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
이 예제에서는 *winvol* 볼륨과 *datamig* SVM에서 *bootlun*, *fdrive*, *gdrive*라는 LUN에 대한 LUN 마이그레이션 검증을 시작하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. 검증 상태를 모니터링합니다.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
이 예에서는 *datamig* SVM의 검증 상태를 모니터링하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
동일한 명령을 실행하여 검증 진행 상황을 추적할 수 있습니다. 검증 작업이 성공적으로 완료되면 *operational-state*가 *completed* 상태로 표시됩니다.

. LUN 검증을 중지합니다.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
이 예에서는 *datamig* SVM에 대한 LUN 검증을 중지하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
LUN을 다시 온라인으로 전환하기 전에 LUN 가져오기 검증을 명시적으로 중지해야 합니다. 그렇지 않으면  `lun online` 명령이 실패합니다. 상태가 검증 완료로 표시되더라도 이 단계는 수동으로 수행해야 합니다.



.다음은 무엇인가요?
link:remove-lun-import-relationship-offline.html["LUN 가져오기 관계 제거"] .
