---
permalink: san-migration/task_configuring_migration_jobs.html 
sidebar: sidebar 
keywords: configure, migration, jobs 
summary: FLI 오프라인 워크플로우에서 소스 LUN 및 대상 LUN을 구성해야 합니다. 
---
= 마이그레이션 작업 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 오프라인 워크플로우에서 소스 LUN 및 대상 LUN을 구성해야 합니다.

.단계
. FLI 마이그레이션의 경우 소스 LUN을 이물질로 표시해야 합니다. 일련 번호를 사용하여 소스 LUN을 외부 LUN으로 표시합니다.
+
[listing]
----

DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542001E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000F }
                   -is-foreign true
----
. 소스 LUN이 외부 LUN으로 표시되어 있는지 확인합니다.
+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     true       foreign        false              83017542001E
HIT-1.3  -     true       foreign        false              83017542000E
HIT-1.4  -     true       foreign        false              83017542000F
3 entries were displayed.
----
. 대상 볼륨을 생성합니다.
+
[listing]
----
DataMig-cmode::*> vol create -vserver datamig winvol aggr1 -size 100g
[Job 5606] Job succeeded: Successful
----
. 각 볼륨에서 기본 스냅샷 정책을 사용하지 않도록 설정합니다. FLI 마이그레이션 전에 기본 Snapshot 복사본이 있는 경우 변경된 데이터를 저장하려면 볼륨에 추가 공간이 필요합니다.
+
[listing]
----
DataMig-cmode::> volume modify -vserver datamig -volume winvol -snapshot-policy none

Warning: You are changing the Snapshot policy on volume winvol to none.  Any Snapshot copies on this volume from the previous policy will not be deleted by
         this new Snapshot policy.
Do you want to continue? {y|n}: y
Volume modify successful on volume winvol of Vserver datamig.
----
. 각 볼륨에 대해 fraction_reserveoption을 0으로 설정하고 Snapshot 정책을 none으로 설정합니다.
+
[listing]
----
DataMig-cmode::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. 볼륨 설정을 확인합니다.
+
[listing]
----
DataMig-cmode::> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamig datamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. 기존 스냅샷 복사본을 삭제합니다
+
[listing]
----
DataMig-cmode::> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
FLI 마이그레이션은 대상 LUN의 모든 블록을 수정합니다. FLI 마이그레이션 전에 볼륨에 기본 또는 기타 Snapshot 복사본이 있으면 볼륨이 가득 차게 됩니다. FLI 마이그레이션이 필요하기 전에 정책을 변경하고 기존 Snapshot 복사본을 제거합니다. 마이그레이션 후 스냅샷 정책을 다시 설정할 수 있습니다.

====
+
[NOTE]
====
LUN create 명령은 파티션 오프셋을 기반으로 크기와 정렬을 감지하고 그에 따라 외부 디스크 옵션을 사용하여 LUN을 생성합니다. 검토는 NetApp 기술 자료 문서 * 정렬되지 않은 I/O란 무엇입니까? * 를 참조하십시오. 또한 일부 I/O는 항상 부분 쓰기이므로 잘못 정렬될 수 있습니다. 예를 들어 데이터베이스 로그가 있습니다.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["정렬되지 않은 I/O란 무엇입니까?"]

. 외부 LUN을 사용하여 대상 LUN을 생성합니다.
+
[listing]
----
DataMig-cmode::*> lun create -vserver datamig -path /vol/winvol/bootlun -ostype windows_2008 -foreign-disk 83017542001E

Created a LUN of size 40g (42949672960)

Created a LUN of size 20g (21474836480)
DataMig-cmode::*> lun create -vserver datamig -path /vol/linuxvol/lvmlun1 -ostype linux -foreign-disk 830175420011

Created a LUN of size 2g (2147483648)
DataMig-cmode::*> lun create -vserver datamig -path /vol/esxvol/bootlun -ostype vmware -foreign-disk 830175420014

Created a LUN of size 20g (21474836480)
----
. 대상 LUN을 나열하고 소스 LUN이 있는 LUN 크기를 확인합니다.
+
[listing]
----
DataMig-cmode::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  unmapped vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  unmapped linux         2GB
datamig   /vol/esxvol/solrdmplun          online  unmapped solaris       2GB
datamig   /vol/winvol/gdrive              online  unmapped windows_2008  3GB
4 entries were displayed.

DataMig-cmode::*>
----
+
[NOTE]
====
FLI 오프라인 마이그레이션의 경우 LUN 임포트 관계를 생성하기 전에 LUN을 igroup에 매핑한 다음 오프라인으로 전환해야 합니다.

====
. 프로토콜 FCP의 호스트 igroup을 생성하고 이니시에이터를 추가합니다. 사이트 설문조사 계획 워크시트의 스토리지 그룹 섹션에서 이니시에이터 WWPN을 찾습니다.
+
[listing]
----
DataMig-cmode::*> lun igroup create -ostype windows -protocol fcp -vserver datamig -igroup dm-rx200s6-21 -initiator 21:00:00:24:ff:30:14:c4,21:00:00:24:ff:30:14:c5

DataMig-cmode::*> lun igroup create -ostype linux -protocol fcp -vserver datamig  -igroup dm-rx200s6-22 -initiator 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84

DataMig-cmode::*> lun igroup create -ostype vmware -protocol fcp -vserver datamig -igroup dm-rx200s6-20 -initiator 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb
----
+
[NOTE]
====
소스와 동일한 LUN ID를 사용합니다. 사이트 조사 계획 워크시트의 소스 LUN 섹션을 참조하십시오.

====
. 대상 LUN을 igroup에 매핑합니다.
+
[listing]
----
DataMig-cmode::*> lun map -vserver datamig -path /vol/winvol/bootlun -igroup dm-rx200s6-21 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/linuxvol/bootlun -igroup dm-rx200s6-22 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/esxvol/bootlun -igroup dm-rx200s6-20 -lun-id 0
----
. 대상 LUN을 오프라인 상태로 전환합니다.
+
[listing]
----
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/bootlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/linuxrdmvlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/solrdmplun
----
. 대상 LUN 및 소스 LUN과의 가져오기 관계를 생성합니다.
+
[listing]
----
DataMig-cmode::*> lun import create -vserver datamig -path /vol/winvol/bootlun -foreign-disk 83017542001E
DataMig-cmode::*> lun import create -vserver datamig -path /vol/linuxvol/ext3lun -foreign-disk 830175420013
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/linuxrdmvlun -foreign-disk 830175420018
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/solrdmplun -foreign-disk 830175420019
----
. 가져오기 작업이 생성되었는지 확인합니다.
+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542000E   /vol/winvol/fdrive  import    stopped
                                                           stopped            0
datamig 83017542000F   /vol/winvol/gdrive  import    stopped
                                                           stopped            0
datamig 830175420010   /vol/linuxvol/bootlun
                                           import    stopped
                                                           stopped            0
3 entries were displayed.
----

