---
permalink: san-migration/task_fli_offline_importing_the_data.html 
sidebar: sidebar 
keywords: fli offline, import data, migration 
summary: FLI 오프라인 마이그레이션을 위해 소스 LUN과 대상 LUN 간에 LUN 가져오기 관계를 만든 후에는 외부 어레이에서 ONTAP 스토리지 시스템으로 데이터를 가져올 수 있습니다. 
---
= ONTAP FLI 오프라인 마이그레이션을 사용하여 외부 어레이에서 데이터 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 오프라인 마이그레이션을 위해 소스 LUN과 대상 LUN 간에 LUN 가져오기 관계를 만든 후에는 외부 어레이에서 ONTAP 스토리지 시스템으로 데이터를 가져올 수 있습니다.

ONTAP 9.17.1부터 ASA r2 시스템에서 FLI 오프라인 마이그레이션을 사용한 외부 LUN 데이터 마이그레이션이 지원됩니다. ASA r2 시스템은 스토리지 계층 구현 방식에서 다른 ONTAP 시스템(ASA, AFF, FAS)과 다릅니다. ASA r2 시스템에서는 스토리지 유닛(LUN 또는 네임스페이스)이 생성될 때 볼륨이 자동으로 생성됩니다. 각 볼륨에는 스토리지 유닛이 하나만 포함됩니다. 따라서 ASA r2 시스템의 경우 볼륨 이름을 지정할 필요가 없습니다.  `-path` LUN을 생성할 때 옵션을 사용하는 대신 저장 장치 경로를 포함해야 합니다.

자세히 알아보세요 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 시스템"^] .

.단계
. 외부 LUN에서 ONTAP LUN으로 데이터 가져오기를 시작합니다.
+
[source, cli]
----
lun import start –vserver <SVM_name> –path <volume_path|storage_unit_path>
----
+
이 예제에서는 *winvol* 볼륨과 *datamig* SVM에서 *bootlun*, *fdrive*, *gdrive*라는 LUN에 대한 데이터 가져오기를 시작하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import start –vserver datamig –path /vol/winvol/bootlun

DataMig-ontap::*> lun import start –vserver datamig –path /vol/winvol/fdrive

DataMig-ontap::*> lun import start –vserver datamig –path /vol/winvol/gdrive
----
. 가져오기 진행 상황을 모니터링합니다.
+
[source, cli]
----
lun import show –vserver <SVM_name> –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
여기서 확인한 진행 상황을 테스트 마이그레이션을 수행한 후 개발한 마이그레이션 성능 추정치와 비교할 수 있습니다.

+
이 예에서는 *datamig* SVM의 가져오기 진행률을 모니터링하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       83               35107077        41943040     00:00:48
3 entries were displayed.
----
. 데이터 가져오기가 성공적으로 완료되었는지 확인하세요.
+
[source, cli]
----
lun import show –vserver <SVM_name> –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
----
+
이 예에서는 *datamig* SVM의 가져오기 상태를 확인하는 명령을 보여줍니다.

+
[listing]
----
DataMig-ontap::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
----
+
가져오기 작업이 성공적으로 완료되면 *작업 상태*가 *완료*로 표시됩니다.



.다음은 무엇인가요?
link:task_fli_offline_verifying_migration_results.html["마이그레이션 결과 확인"] .
