---
permalink: san-migration/task_fli_online_performing_a_disruptive_cutover.html 
sidebar: sidebar 
keywords: fli online, perform, disruptive, cutover 
summary: 이 예는 FLI 온라인 마이그레이션 프로세스에서 무중단 컷오버를 수행하는 일반적인 단계를 보여줍니다. 
---
= FLI 온라인: 운영 중단 컷오버 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 예는 FLI 온라인 마이그레이션 프로세스에서 무중단 컷오버를 수행하는 일반적인 단계를 보여줍니다.

Windows, Linux 및 ESXi에 대한 호스트 개선 연습은 이 가이드의 후속 섹션과 호스트 운영 체제 및 호스트 연결 키트 문서를 참조하십시오.

.단계
. 외부 스토리지에서 소스 LUN이 매핑되는 스토리지 그룹을 표시합니다.
+
해당 명령에 대한 자세한 내용은 공급업체 설명서를 참조하십시오.

. 가져오는 LUN이 ESXi 호스트용 LUN인 경우, _ESXi caw/ATS 개선_항목에 대한 지침을 검토하고 따르십시오.
. 호스트에서 소스 LUN 매핑을 해제합니다.
+
[NOTE]
====
여기서 중단 기간이 시작됩니다.

====
+
매핑 해제 명령이 실행된 직후 중단이 시작됩니다. 일반적으로 중단 기간은 분 단위로 측정할 수 있습니다. 중단 기간은 새 NetApp 타겟의 호스트를 재가리키고 LUN을 검색하는 데 걸린 시간입니다.

+
igroup에서 호스트(이니시에이터)를 제거하면 igroup에 매핑된 다른 LUN에 영향을 미치므로 이 LUN이 이 igroup에 매핑된 유일한 LUN인지 확인해야 합니다. 해당 명령에 대한 자세한 내용은 공급업체 설명서를 참조하십시오.

. 호스트 이니시에이터가 더 이상 존재하지 않는지 확인합니다.
. ONTAP 클러스터에서 대상 LUN을 온라인 상태로 전환하고 매핑되었는지 확인합니다.
+
[listing]
----
cluster::*> lun online -vserver fli -path /vol/fli_vol/OnlineFLI_LUN
----
. LUN이 온라인 상태인지 확인합니다.
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  mapped   windows_2008  1TB
----
. 호스트에서 디스크를 재검색하고 ONTAP 대상에서 LUN을 찾은 다음 DSM이 LUN을 확보했는지 확인합니다.
+
[NOTE]
====
여기서 중단 기간이 종료됩니다.

====
. 모든 예상 경로를 볼 수 있는지 확인하고 이벤트 로그를 확인하여 오류가 없는지 확인합니다.
+
이때 분석 및 계획 단계에서 운영 중단을 야기하는 매우 중요한 호스트 개선 작업이 없는 한 마이그레이션의 중단 부분이 완료됩니다.

+
LUN이 온라인 상태로 매핑되고 호스트에서 새로운 ONTAP 호스팅 LUN을 마운트할 수 있습니다. 읽기는 ONTAP 어레이를 통해 소스 LUN으로 전달되고, 쓰기는 새로운 ONTAP 호스팅 LUN과 원본 소스 LUN 모두에 기록됩니다. 마이그레이션이 완료되고 LUN 관계가 끊어질 때까지 소스 LUN과 대상 LUN은 동기화된 상태를 유지합니다.


