---
permalink: post-migration-performance/esxi-remediation.html 
sidebar: sidebar 
keywords: esxi remediation, vmfs, ats, caw, vaai, vmkfstools, datastore, online fli, foreign lun import, fli, vmware, ats-only 
summary: 온라인 FLI 가져오기 관계를 통해 제공될 때 마운트를 방해할 수 있는 ATS 전용 VMFS 헤더가 있는 VMware ESXi 데이터 저장소를 수정합니다. 
---
= ONTAP FLI ESXi VMFSS ATS/CAW 문제 해결을 수행합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
온라인 FLI 마이그레이션 중에 임시 가져오기 관계는 VMware ATS 또는 CAW(VAAI Atomic Test and Set 또는 SCSI Compare And Write)를 지원하지 않습니다. 데이터스토어가 VMFS5이고 ATS를 지원하는 스토리지에 생성된 경우 VMware는 VMFS 헤더를 "ATS 전용"으로 표시할 수 있습니다. 이 경우 온라인 FLI 관계를 통해 데이터스토어를 마운트할 때 오류가 발생할 수 있습니다.

.이 작업에 관하여
* "ATS 전용" 설정은 데이터스토어의 첫 번째 익스텐트에 있는 VMFS 헤더에 저장됩니다. 데이터스토어가 여러 익스텐트에 걸쳐 있는 경우 첫 번째 익스텐트만 수정하면 됩니다.
* 데이터 저장소가 여러 ESXi 호스트에서 공유되는 경우 일반적으로 한 호스트에서 업데이트하는 것으로 충분합니다. 다른 호스트는 재검색 및 재마운트 후 변경 사항을 적용합니다.
* ATS 전용 모드를 변경하는 동안에는 데이터스토어에 대한 활성 I/O 작업이 실행 중이면 안 됩니다. VMware 지침에 따라 변경 사항을 적용하려면 VM을 비우고 마이그레이션하거나 종료한 후 필요에 따라 마운트 해제 및 다시 마운트해야 합니다.


.단계
. 데이터 저장소의 현재 ATS 모드를 확인하십시오.
+
VMFS 볼륨에 대해 ESXi 호스트에서 다음을 실행하십시오.

+
[source, cli]
----
vmkfstools -Ph -v1 /vmfs/volumes/<DATASTORE_NAME_OR_UUID>
----
. ATS 전용을 비활성화합니다.
+

IMPORTANT: 변경 계획에 따라 필요한 경우 VM이 마이그레이션되고 종료되었는지, 데이터스토어가 모든 호스트에서 마운트 해제되었는지 확인하십시오. 첫 번째 익스텐트 LUN(naa.*)의 장치 경로에서 실행하십시오:

+
[source, cli]
----
vmkfstools --configATSOnly 0 /vmfs/devices/disks/naa.<naa_id>:1
----
+
이렇게 하면 비 ATS 잠금(공용)을 허용하도록 볼륨이 변경됩니다.

. 호스트가 업데이트된 모드를 다시 읽도록 스토리지 어댑터를 다시 검색하거나 데이터 저장소를 다시 마운트하십시오.
. ATS를 다시 활성화하십시오.
+
마이그레이션이 완료된 후 ATS 전용 동작을 복원하려면 다음을 수행합니다.

+
[source, cli]
----
vmkfstools --configATSOnly 1 /vmfs/devices/disks/naa.<naa_id>:1
----
. 변경 사항을 적용하려면 다시 스캔하고 다시 마운트하십시오.

