---
permalink: configure/fc-configure-adapter-initiator-mode.html 
sidebar: sidebar 
keywords:  
summary:  
---
= ONTAP 외부 LUN 가져오기(FLI) 마이그레이션을 위한 이니시에이터 모드로 FC 어댑터를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP FLI over FC를 사용하려면 ONTAP 측에 이니시에이터 모드의 FC 어댑터가 필요합니다. 사용 가능한 이니시에이터 포트가 없는 경우 FC 타겟 어댑터 포트를 이니시에이터 모드로 변환해야 할 수 있습니다. 또한 FC 어댑터에 활성 FC LIF가 있는 경우 해당 활성 FC LIF를 동일한 패브릭 내의 다른 어댑터 포트로 이동해야 합니다.

.단계
. 사용 가능한 FC 어댑터를 확인하십시오.
+
[source, cli]
----
fcp adapter show -status-oper online
----
+
*출력 예*

+
[listing]
----
  (network fcp adapter show)
                      Connection  Port    Admin    Operational
Node         Adapter  Established Address Status   Status          Topology
------------ -------- ----------- ------- -------- --------------- --------
ssan-a50-06a 3a       true        640a00  up       online          fabric
ssan-a50-06b 3b       true        640a00  up       online          fabric
ssan-a50-07a 3a       true        640e00  up       online          fabric
ssan-a50-07b 3b       true        640d00  up       online          fabric
----
. 타겟 FC 어댑터 포트를 오프라인으로 전환하십시오.
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter>> -status-admin down;
----
+
*출력 예*

+
[listing]
----
fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin down;
----
. 어댑터의 상태가 다운인지 확인하십시오.
+
[source, cli]
----
fcp adapter show -node <node_name> -adapter <adapter>> -fields status-admin
----
+
*출력 예*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter show -node ssan-a50-06a -adapter 3a -fields status-admin

node         adapter status-admin
------------ ------- ------------
ssan-a50-06a 3a      down
----
. FC 어댑터 포트를 타겟 모드에서 이니시에이터 모드로 변환합니다.
+
[source, cli]
----
system node hardware unified-connect modify -node <node_name> -adapter <adapter> -type initiator
----
+
*예*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect modify -node ssan-a50-06a -adapter 3a -type initiator

Any changes will take effect after rebooting the system. Use the "system node reboot" command to reboot.
----
. 어댑터를 다시 온라인으로 전환하세요.
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter> -status-admin up;
----
+
*예*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin up;
----
. 어댑터가 다시 온라인 상태이고 이니시에이터 모드인지 확인하십시오.
+
[source, cli]
----
system node hardware unified-connect show
----
+
*예*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect show
                       Current  Current    Pending  Pending    Admin
Node          Adapter  Mode     Type       Mode     Type       Status
------------  -------  -------  ---------  -------  ---------  -----------
ssan-a50-06a  3a       fc       target     -        initiator  offline << pending node reboot
ssan-a50-06b  3b       fc       target     -        -          online
ssan-a50-07a  3c       fc       target     -        -          online
ssan-a50-07a  3d       fc       initiator  -        -          online <<< already converted
ssan-a50-06-07::*>
----

